FROM golang:1.20rc3-alpine3.17 as builder
ENV APP_HOME=/app
WORKDIR "$APP_HOME"
COPY src/ .

RUN go mod download
RUN go mod verify
RUN go build -o goleader

FROM alpine:3.14 

COPY --from=builder /app/goleader .







